### ISSUE TITLE
Add `just_finished` function in addition to `is_finished`

### ISSUE THREAD

**Issue by PraxTube** [KirmesBude/bevy_trickfilm#23]
I have found myself needing a `just_finished` function quite often to for example signal an event that might get fired multiple times with just an `is_finished` (because of possible frame delays). It would just fire a single time per animation similar to the `Timer.just_finished`. Just curious what your thoughts on this are? Maybe I am just overcomplicating things again.

**Comment by KirmesBude** [comment]
That makes sense, yes.
Might be worth to finally think about Events (and/or Triggers?) for this use case as well. But just_finished seems useful on it's own. If you have an idea on how to implement it go ahead, otherwise I will try to throw something together next week.

**Comment by PraxTube** [comment]
Alright cool, I will try to hack something together tomorrow.

Ohhh, right Events are also a possibility, I didn't think about that at all. I will give that some thought as well.

**Comment by KirmesBude** [comment]
I just remembered that I used timers internally in the past. I think I changed it to the way it is now so it is closer to the (3d) animation stuff from bevy, but I do not think we ultimately gained a lot from that.
Maybe we should go back to timers to get some of this stuff for "free".

**Comment by PraxTube** [comment]
Yeah I was just going through the `Timer.just_finished` to get an idea of how they implemented it. It would be fairly hard to add `just_finished` without also adding quite a bit of state. I wouldn't mind going with Timers.

**Comment by PraxTube** [comment]
I also thought about how to add Events, but I actually don't know if that is such a good idea. For example, would you fire an Event with the ID of the entity the animation is on (say whenever an animation just finished)? Depending on how many animations you have this might be quite a lot and the user would still need to check if that event is the one he actually cares about.

What I could imagine works better here is to add a `Component` like a `AnimationJustFinished` to the entity where the `AnimationPlayer2D` is on. Then you could query for `Added<AnimationJustFinished` and know for certain that the animation finished. I am not a huge fan of this control flow though, but I can't really think of a way in that `Event`s are really useful, maybe you have some.

**Comment by KirmesBude** [comment]
I am not sure about the performance implications of adding/removing components like that. Feels kinda weird anyways, but I need to think about it a bit more.
In general the ergonomics on how to interface with he animationplayer are not ideal.

**Comment by PraxTube** [comment]
Yeah I also don't really like it, I first saw this in the [`seldom_state`](https://github.com/Seldom-SE/seldom_state) crate, where they add/remove the state on the entity whenever a transition occurs (this happens probably just as often as an animations ends). Though I don't think something like this is required, I personally think the current workflow is quite alright, the initialization of an `AnimationPlayer2D` might be a bit strange, but apart from that I think it's pretty smooth.

**Comment by KirmesBude** [comment]
I tried with timers in #25, but I did not really like it. Maybe I did not do it the best way, but negative speeds/reverse animation do not seem to work well at all with timers.
Instead I have #26, which just adds just_finished on top. @PraxTube mind taking a look?
