### ISSUE TITLE
Get animation duration in AnimationPlayer2D

### ISSUE THREAD

**Issue by PraxTube** [KirmesBude/bevy_trickfilm#34]
I need to know about the current animations percentage elepased (0-100%). I can use elapsed to know the absolute elapsed time, but I would need to [use this](https://github.com/KirmesBude/bevy_trickfilm/blob/5bfb6acce905f97b88cfdcf12fada622b0f2815c/src/animation/animation_spritesheet.rs#L51) to also get the duration and then get the relative eleapsed time.

Adding something like either `max_frames()` or `duration()` to AnimationPlayer2D would solve this and would be pretty easy to implement I think (I would probably add the method to PlayingAnimation2D), what do you think?

**Comment by KirmesBude** [comment]
Yeah, go ahead. It you take `Assets<Animation2DClip>` as input it is straight forward.
If you copy over duration from the clip, you need to make sure to do that in the animation update system so hot reloading still works.
